# prompts.py — Templates de questions pour tous les domaines

PROMPTS = [
    "Explique {}.",
    "Présente {} en détail.",
    "Décris {} de façon approfondie.",
    "Analyse {}.",
    "Résume les points essentiels de {}.",
    "Quels sont les enjeux de {} ?",
    "Pourquoi {} est-il important dans le monde contemporain ?",
    "Compare {} avec un sujet similaire.",
    "Quelles sont les origines et causes de {} ?",
    "Quelles sont les conséquences de {} sur la société ?",
    "Quels sont les avantages et les limites de {} ?",
    "Quels sont les principaux acteurs de {} ?",
    "Retrace l'histoire et l'évolution de {}.",
    "Comment fonctionne {} ?",
    "Quel est l'impact de {} sur le monde actuel ?",
    "Quelles sont les controverses autour de {} ?",
    "Quelles sont les perspectives d'avenir de {} ?",
    "Comment {} a-t-il évolué au fil du temps ?",
    "Quels défis pose {} pour l'humanité ?",
    "Quel rôle joue {} dans la société moderne ?",
    "Quelles sont les théories principales concernant {} ?",
    "Comment {} influence-t-il notre quotidien ?",
    "Quelle est la place de {} dans le monde contemporain ?",
    "Quels sont les débats actuels autour de {} ?",
    "Comment {} est-il perçu dans différentes cultures ?",
    "Quelles découvertes ou avancées récentes concernent {} ?",
    "Quel est le lien entre {} et les enjeux globaux actuels ?",
    "Comment enseigne-t-on {} aujourd'hui ?",
    "Quelles sont les grandes figures associées à {} ?",
    "Quels exemples concrets illustrent {} ?"
]
